apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cnpg-postgres-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  groups:
  - name: cnpg.rules
    rules:
    - alert: PostgresInstanceDown
      expr: cnpg_collector_up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Postgres instance is down"
        description: "A CNPG Postgres instance has been unavailable for more than 1 minute"

    - alert: PostgresReplicationLagHigh
      expr: cnpg_pg_replication_lag > 5
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High replication lag"
        description: "Replication lag is above 5 second for 1 minutes"
    # fix disk usage
    - alert: PostgresDiskUsageHigh
      expr: cnpg_pg_data_disk_usage_percent > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Postgres disk usage high"
        description: "Postgres data disk usage above 80%"
