apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-cluster-app
  namespace: backend
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcs-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: cnpg-cluster-app
  target:
    name: cnpg-cluster-app
    creationPolicy: Owner
