apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-external-secret
  namespace: database
spec:
  refreshInterval: "24h"
  target:
    name: cnpg-cluster-app
    creationPolicy: Merge
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .password }}"
        pgpass: "cluster-cnpg-rw:5432:app:app:{{ .password }}"
        jdbc-uri: "jdbc:postgresql://cluster-cnpg-rw.default:5432/app?password={{ .password }}&user=app"
        uri: "postgresql://app:{{ .password }}@cluster-cnpg-rw.default:5432/app"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pg-password-generator