apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-sa
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: secrets-sa@cnpg-project.iam.gserviceaccount.com

---

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcs-backend
spec:
  provider:
    gcpsm:
      projectID: cnpg-project
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: secrets-sa
            namespace: external-secrets 
