apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: database
spec:
  instances: 1    # number of Postgres instances
  storage:
    size: 5Gi           # PVC size
